# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20161101_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, verbose_name='website'),
        ),
    ]
